
export const CHANGE_TREE_STATUS = 'CHANGE_TREE_STATUS'
export const CHANGE_CONTENT_SECTION="CHANGE_CONTENT_SECTION"
export const GET_SECTION_DATA="GET_SECTION_DATA"
export const GET_TREE_DATA="GET_TREE_DATA"
export const GET_QUESTION_DATA="GET_QUESTION_DATA"
export const CUR_COURSE_ID="CUR_COURSE_ID";